# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    #run_tests(device: "iPhone 13 Pro Max", scheme: "sample AppTests")
    #run_tests(devices: ["iPhone 13", "iPhone 13 Pro Max"], open_report: true, only_testing: "sample AppTests")
    #run_tests(devices: ["iPhone 13 Pro Max"], open_report: true, skip_testing: "sample AppUITests")
    run_tests(device: "iPhone 13 Pro Max", only_testing: "sample AppTests")
  end

  # 現在のブランチへコミット
  lane :commit_push do |options|
     git_commit(path: "./*", message: "gitからビルドアップ")
     push_to_git_remote(tags:false)
  end

  # version build 番号を更新して.ipa ファイルの作成
  lane :build do |options|
    # バージョン更新
    if options[:version] #version引数があった場合バーションをインクリメントする※例：　fastlane build version:minor 
      increment_version_number_in_xcodeproj(
        #version_number: options[:version], # 引数で指定
        #bump_type: 'patch' #1.0.0←ここ
        #bump_type: 'minor', #1.0←ここ
        #bump_type: 'major', #1←ここ
        bump_type: options[:version],
        xcodeproj: "./sample App.xcodeproj",
        omit_zero_patch_version: true # trueの場合はパッチのゼロを省略.0は1.0になる※bump_typeを指定する必要があります
      )
    end
    # 上げたバージョン取得
    version = get_version_number_from_xcodeproj(
                xcodeproj: "./sample App.xcodeproj"
              )
    
    trailing_number = get_build_number.split('.').last.to_i
    # get_version_numberを取得、ビルド番号の末尾の値を1つ増やす
    next_build_number = "#{version}.#{trailing_number + 1}"
    # ビルド番号を指定し、更新
    increment_build_number(build_number: next_build_number)
    
    # .ipaファイルの作成
    build_ios_app(
      scheme: "sample App",
      configuration: "Debug",
      export_method: "development",
      output_directory: "./ipa/" + Time.new.strftime("%Y%m%d/%H%M"),
      output_name: "MyApp.ipa",
      export_options: {
         provisioningProfiles: {
          "co.jp.sample.sampleApp" => "co.jp.sample.sampleApp",
         }
      }
    )
  end

  # teamIDとbundle_identifierの紐づけ
  private_lane :settings_team_id_and_bundle_identifier do
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV['TEAM_ID'],
      code_sign_identity: "iPhone Developer",
      bundle_identifier: ENV['BUNDIE_IDENTIFIER']
    )
  end

  # GitHub用 version build 番号を更新して.ipa ファイルの作成
  lane :build_GitHub do |options|
    settings_team_id_and_bundle_identifier

    trailing_number = get_build_number.split('.').last.to_i
    # get_version_numberを取得、ビルド番号の末尾の値を1つ増やす
    next_build_number = "#{get_version_number}.#{trailing_number + 1}"
    # ビルド番号を指定し、更新
    increment_build_number(build_number: next_build_number)

    # .ipaファイルの作成
    build_ios_app(
      scheme: "sample App",
      configuration: "Debug",
      export_method: "development",
      output_directory: "./build/ipa/",
      output_name: "MyApp.ipa",
      export_options: {
         provisioningProfiles: {
          ENV['BUNDIE_IDENTIFIER'] => ENV['BUNDIE_IDENTIFIER'],
         }
      }
    )
  end
end
