# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_iOS: # jobに名前をつけられる

    name: Build for iOS # GitHubに表示されるジョブの名前
    runs-on: macos-latest # ジョブを実行するマシーンの種類

    steps: #一連のタスク

      # チェックアウト
      - name: Checks-out my repository
        uses: actions/checkout@v2
      
      # Xcode 13.2.1 を使う
      - name: Select Xcode version 
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'

      # バージョン確認
      - name: Show Xcode version
        run: xcodebuild -version

      # Bundleインストール
      - name: Bundle Install
        run: bundle install
      
      # 証明書の生成
      - name: Import Provisioning Profile
        run: | # Provisioning Profilesを置くべきディレクトリにデコードしている
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/9373ec01-333c-40a2-9fd1-03fa0509e0ac.mobileprovision

      # 署名をする
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1 
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
      
      # .ipaファイルを作成する
      - name: Upload a new build to .ipa
        env:
          BUNDIE_IDENTIFIER: ${{ secrets.BUNDIE_IDENTIFIER }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: bundle exec fastlane build